use_frameworks!

platform :ios, '8.0'

target 'HZSWeakTimerTarget_Example' do
  pod 'HZSWeakTimerTarget', :path => '../'

  target 'HZSWeakTimerTarget_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
